#+STARTUP: overview hidestars logdone
#+COLUMNS: %38ITEM(Details) %7TODO(To Do) %TAGS(Context)
#+OPTIONS: tags:t timestamp:t todo:t TeX:t LaTeX:t
#+OPTIONS: skip:t @:t ::t |:t ^:t f:t
#+LANGUAGE: en
#+TITLE: Cryptator

[[https://opensource.org/licenses/BSD-3-Clause][https://img.shields.io/badge/License-BSD%203--Clause-blue.svg]]

Cryptator is distributed under BSD 3-Clause License (Copyright (c) 2021, Université Côte d'Azur).

* Documentation, Support and Issues

 Look for the most up-to-date documentation on the web site, or javadoc.

* Download and Installation

  In the following, we distinguish two usages:
    - as a standalone application: the jar file includes all required dependencies,
    - as a library: the jar file excludes all dependencies.

** Prerequisites
  This project works on 32 bits and 64 bits environment.

  This project requires:

  Requirements:

  - JDK 8+
  - Maven 3+

** Inside a maven project

First, you must build from source and install it into your local .m2 repository.
Then, you only have to edit your pom.xml to declare the following library dependency:

#+BEGIN_EXAMPLE
<dependency>
   <groupId>fr.univ-cotedazur</groupId>
   <artifactId>cryptator</artifactId>
   <version>0.0.1-SNAPSHOT</version>
</dependency>
#+END_EXAMPLE

** As a stand-alone application

 The jar file contains all required dependencies.
 The next step is simply to add the jar file to your classpath of your application.
 Note that if your program depends on dependencies declared in the jar file, you should consider using eps4j-core as a library.

** As a library

   The jar file does not contains any dependencies, as of being used as a dependency of another application.
   The next step is to add the jar file to your classpath of your application and also add the required dependencies.

** Building from source

   This project uses the Cross-platform Maven build system.
   : mvn clean package
   or to skip unit tests
   : mvn clean package -DskipTests=true

*** Installing

    Once the project has been built, execute
    : mvn install
    or to skip tests
    : mvn install -DskipTests=true
